// Phase 12 — Creative toolkit. REAL executable image generation.
//
// 1 tool: image-gen
//   Provider: OpenAI DALL-E 3 (env OPENAI_API_KEY).
//   Auto-save vào media_assets table với imported_from='agent-run-N'.
//   Output: mediaAssetId + URL.

import 'server-only';
import OpenAI from 'openai';
import { sql } from 'drizzle-orm';
import { getDb } from '@mos2/db';
import { register, z } from './registry';
import { uploadToR2 } from '@/lib/r2';

register({
  id: 'image-gen',
  schema: z.object({
    prompt: z.string().min(5).max(4000),
    size: z.enum(['1024x1024', '1024x1792', '1792x1024']).default('1024x1024'),
    quality: z.enum(['low', 'medium', 'high']).default('medium'),
    title: z.string().max(200).optional(),  // dùng làm filename
  }),
  output: z.object({
    mediaAssetId: z.number(),
    url: z.string().min(1),  // data URL (gpt-image-2 b64) hoặc http URL
    width: z.number(),
    height: z.number(),
    revisedPrompt: z.string().nullable(),
  }),
  sideEffect: 'write',
  costEstimateCents: 6,                     // gpt-image-2 medium ~$0.053 1024²
  timeoutMs: 90_000,
  fn: async (input, ctx) => {
    if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY chưa set');
    const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    // gpt-image-2 (mới nhất #1 — xem memory reference_image_gen_model).
    // Trả base64 (không trả url) → lưu data URL (bỏ bug url tạm hết hạn).
    const res = await client.images.generate({
      model: 'gpt-image-2',
      prompt: input.prompt,
      size: input.size,
      quality: input.quality,
      n: 1,
    });
    const img = res.data?.[0];
    const b64 = img?.b64_json;
    if (!b64) throw new Error('gpt-image-2 không trả b64');
    const buf = Buffer.from(b64, 'base64');
    const [w, h] = (input.size ?? '1024x1024').split('x').map(Number);

    const db = getDb();
    if (!db) throw new Error('DATABASE_URL not configured');
    const filename = (input.title ?? input.prompt.slice(0, 60)).replace(/[^a-zA-Z0-9-_ ]/g, '').trim() + '.png';
    const r2url = await uploadToR2(`agent/${ctx.projectId}/${Date.now()}.png`, buf, 'image/png');
    const storeUrl = r2url ?? `data:image/png;base64,${b64}`;
    const insRows = await db.execute(sql`
      INSERT INTO media_assets (
        tenant_id, project_id, kind, filename, url, mime_type,
        size_bytes, width, height, source, tags, notes
      ) VALUES (
        'self', ${ctx.projectId}, 'image', ${filename}, ${storeUrl}, 'image/png',
        ${buf.length}, ${w}, ${h}, 'gen',
        ${JSON.stringify(['agent-generated', 'gpt-image-2', r2url ? 'r2' : 'data-url'])}::jsonb,
        ${`Generated by agent run ${ctx.agentRunId ?? '?'}. Prompt: ${input.prompt.slice(0, 200)}`}
      ) RETURNING id
    `);
    const r = (insRows as unknown as Array<{ id: number | string }>)[0]!;
    return {
      mediaAssetId: Number(r.id),
      url: storeUrl,
      width: w!,
      height: h!,
      revisedPrompt: img.revised_prompt ?? null,
    };
  },
});

export const CREATIVE_TOOLKIT_LOADED = true;
