// Phase 12 — Creative toolkit. REAL executable image generation.
//
// 1 tool: image-gen
//   Provider: OpenAI DALL-E 3 (env OPENAI_API_KEY).
//   Auto-save vào media_assets table với imported_from='agent-run-N'.
//   Output: mediaAssetId + URL.

import 'server-only';
import OpenAI from 'openai';
import { sql } from 'drizzle-orm';
import { getDb } from '@mos2/db';
import { register, z } from './registry';

register({
  id: 'image-gen',
  schema: z.object({
    prompt: z.string().min(5).max(4000),
    size: z.enum(['1024x1024', '1024x1792', '1792x1024']).default('1024x1024'),
    quality: z.enum(['standard', 'hd']).default('standard'),
    style: z.enum(['natural', 'vivid']).default('vivid'),
    title: z.string().max(200).optional(),  // dùng làm filename
  }),
  output: z.object({
    mediaAssetId: z.number(),
    url: z.string().url(),
    width: z.number(),
    height: z.number(),
    revisedPrompt: z.string().nullable(),
  }),
  sideEffect: 'write',
  costEstimateCents: 4,                     // ~$0.04 standard / $0.08 HD
  timeoutMs: 60_000,
  fn: async (input, ctx) => {
    if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY chưa set');
    const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const res = await client.images.generate({
      model: 'dall-e-3',
      prompt: input.prompt,
      size: input.size,
      quality: input.quality,
      style: input.style,
      n: 1,
    });
    const img = res.data?.[0];
    if (!img?.url) throw new Error('DALL-E không trả url');
    const [w, h] = (input.size ?? '1024x1024').split('x').map(Number);

    // Save vào media_assets. URL = OpenAI temporary CDN (expire ~1h).
    // Future: download → S3 + store stable URL.
    const db = getDb();
    if (!db) throw new Error('DATABASE_URL not configured');
    const filename = (input.title ?? input.prompt.slice(0, 60)).replace(/[^a-zA-Z0-9-_ ]/g, '').trim() + '.png';
    const insRows = await db.execute(sql`
      INSERT INTO media_assets (
        tenant_id, project_id, kind, filename, url, mime_type,
        width, height, source, tags, notes
      ) VALUES (
        'self', ${ctx.projectId}, 'image', ${filename}, ${img.url}, 'image/png',
        ${w}, ${h}, 'gen',
        ${JSON.stringify(['agent-generated', 'dall-e-3'])}::jsonb,
        ${`Generated by agent run ${ctx.agentRunId ?? '?'}. Original prompt: ${input.prompt.slice(0, 200)}`}
      ) RETURNING id
    `);
    const r = (insRows as unknown as Array<{ id: number | string }>)[0]!;
    return {
      mediaAssetId: Number(r.id),
      url: img.url,
      width: w!,
      height: h!,
      revisedPrompt: img.revised_prompt ?? null,
    };
  },
});

export const CREATIVE_TOOLKIT_LOADED = true;
