BEGIN;
CREATE TABLE IF NOT EXISTS scene_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL DEFAULT 'self',
  platform_key text NOT NULL,
  handle text NOT NULL,
  display_name text,
  scraped_meta jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, platform_key, handle)
);
ALTER TABLE people ADD COLUMN IF NOT EXISTS identity_id bigint REFERENCES scene_identities(id);
ALTER TABLE people ADD COLUMN IF NOT EXISTS account_id bigint;

-- backfill identities (canonical x->twitter, bsky->bluesky giữ nguyên vì lookup chỉ alias x/twitter)
INSERT INTO scene_identities (tenant_id, platform_key, handle, display_name, scraped_meta)
SELECT 'self',
       CASE WHEN platform_key='x' THEN 'twitter' ELSE platform_key END,
       handle,
       (array_agg(display_name) FILTER (WHERE display_name IS NOT NULL))[1],
       (array_agg(scraped_meta) FILTER (WHERE scraped_meta IS NOT NULL))[1]
FROM people WHERE handle IS NOT NULL AND handle <> ''
GROUP BY 1,2,handle
ON CONFLICT (tenant_id, platform_key, handle) DO NOTHING;

-- link people -> identity
UPDATE people p SET identity_id = i.id
FROM scene_identities i
WHERE i.tenant_id='self'
  AND i.platform_key = CASE WHEN p.platform_key='x' THEN 'twitter' ELSE p.platform_key END
  AND i.handle = p.handle;
COMMIT;
SELECT (SELECT count(*) FROM scene_identities) AS identities,
       (SELECT count(*) FROM people) AS people_rows,
       (SELECT count(*) FROM people WHERE identity_id IS NULL) AS unlinked;
BEGIN;
UPDATE people SET account_id = 0 WHERE account_id IS NULL;
ALTER TABLE people ALTER COLUMN account_id SET DEFAULT 0;
ALTER TABLE people ALTER COLUMN account_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS people_proj_ident_acct_uidx ON people (project_id, identity_id, account_id);
COMMIT;
SELECT indexname FROM pg_indexes WHERE tablename='people' AND indexdef ILIKE '%unique%';

-- Phase 3: DROP INDEX IF EXISTS people_proj_plat_handle_uidx; (applied after endpoints switched to ON CONFLICT (project_id,identity_id,account_id))
