// Shared GSC stats loader for projects with a public website.
// Pulls daily JSON snapshot generated by /usr/local/bin/gsc-check.php on the server.

import type { Mode, Kpi } from '@/lib/mock/types';

const GSC_JSON_URL = 'https://militarymarkdown.com/wp-content/uploads/phase7/gsc-latest.json';

type GscSiteStats = {
  pages_with_impressions_7d: number;
  clicks_7d: number;
  impressions_7d: number;
  avg_position_7d: number;
  sitemaps_count: number;
  sitemap_urls_submitted: number;
  sitemap_urls_indexed: number;
  period: string;
};

type GscPayload = {
  updated_at: string;
  sites: Record<string, GscSiteStats>;
};

async function loadGsc(): Promise<GscPayload | null> {
  try {
    const r = await fetch(GSC_JSON_URL, { next: { revalidate: 600 } });
    if (!r.ok) return null;
    return (await r.json()) as GscPayload;
  } catch {
    return null;
  }
}

function pickSite(payload: GscPayload, domain: string): GscSiteStats | null {
  const keys = [
    `sc-domain:${domain}`,
    `https://${domain}/`,
    `https://www.${domain}/`,
    `http://${domain}/`,
  ];
  for (const k of keys) {
    if (payload.sites[k]) return payload.sites[k];
  }
  return null;
}

export async function gscKpisForDomain(domain: string): Promise<Kpi[]> {
  const payload = await loadGsc();
  if (!payload) return [];
  const s = pickSite(payload, domain);
  if (!s) return [];
  return [
    {
      label: 'IMPRESSIONS',
      unit: '7D',
      val: String(s.impressions_7d),
      delta: s.impressions_7d > 0 ? 'GSC live' : 'no data yet',
      tone: s.impressions_7d > 0 ? 'up' : 'flat',
      primary: true,
    },
    {
      label: 'CLICKS',
      unit: '7D',
      val: String(s.clicks_7d),
      delta: s.clicks_7d > 0 ? `${(s.clicks_7d / Math.max(1, s.impressions_7d) * 100).toFixed(1)}% CTR` : '—',
      tone: s.clicks_7d > 0 ? 'up' : 'flat',
    },
    {
      label: 'AVG POSITION',
      unit: 'SERP',
      val: s.avg_position_7d > 0 ? s.avg_position_7d.toFixed(1) : '—',
      delta: s.pages_with_impressions_7d > 0 ? `${s.pages_with_impressions_7d} pages` : '',
      tone: s.avg_position_7d > 0 && s.avg_position_7d < 10 ? 'up' : 'flat',
    },
    {
      label: 'SITEMAP URLs',
      unit: 'SUBMITTED',
      val: String(s.sitemap_urls_submitted),
      delta: `${s.sitemaps_count} sitemap(s)`,
      tone: 'flat',
    },
  ];
}

export async function applyGscOverrides(mode: Mode, project: { id: string; name: string; website?: string | null }): Promise<Mode> {
  const url = project.website || '';
  const domain = url.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '');
  if (!domain) return mode;
  const kpis = await gscKpisForDomain(domain);
  if (!kpis.length) return mode;
  return {
    ...mode,
    pageTitle: project.name,
    pageSub: `Live SEO from Google Search Console — ${domain}`,
    kpis,
    suggestions: [],
    revChart: undefined,
    revData: [],
    topList: [],
  };
}
